import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { Navbar } from "./_components/navbar";
import { TRPCReactProvider } from "~/trpc/react";
import { auth } from "~/server/auth"; 

export const metaMetadata = {
  title: "WireHouse App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth(); 

  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <header>
          <Navbar session={session} /> 
        </header>
        <main className="container mx-auto py-4"> 
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </main>
      </body>
    </html>
  );
}